### ISSUE TITLE
Setup Not Working

### ISSUE THREAD

**Issue by jezzerus** [rllynch/smartthings_cli#1]
Hi,

I am having an issue running through setup, i get the following errors

Traceback (most recent call last):
  File "/usr/bin/smartthings_cli", line 9, in <module>
    load_entry_point('smartthings-cli==1.0', 'console_scripts', 'smartthings_cli')()
  File "/usr/lib/python3.5/site-packages/smartthings_cli-1.0-py3.5.egg/smartthings_cli/smartthings_cli.py", line 256, in main
  File "/usr/lib/python3.5/site-packages/smartthings_cli-1.0-py3.5.egg/smartthings_cli/smartthings_cli.py", line 96, in get_access_token
KeyError: 'access_token'

**Comment by rllynch** [comment]
I just tried it with Python 3.5 and it works for me.  The error indicates an invalid response from the SmartThings servers.  Please make sure you're authorizing the scripts to access at least one SmartThings device.

**Comment by jezzerus** [comment]
Hi thanks for coming back, i have the hub and devces authroized, and i get and authcode back, it just bombs out right after that

**Comment by jezzerus** [comment]
sratch that i generated a new client secret in the app and that fixed it
