### ISSUE TITLE
TLS issues?

### ISSUE THREAD

**Issue by c240amg** [rllynch/smartthings_cli#6]
After following your instructions, I get this:

```
smartthings_cli --clientid <id> --clientsecret <secret>

Traceback (most recent call last):
  File "/usr/local/bin/smartthings_cli", line 9, in <module>
    load_entry_point('smartthings-cli==1.0', 'console_scripts', 'smartthings_cli')()
  File "build/bdist.macosx-10.13-intel/egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "build/bdist.macosx-10.13-intel/egg/pkg_resources/__init__.py", line 2721, in load_entry_point
  File "build/bdist.macosx-10.13-intel/egg/pkg_resources/__init__.py", line 2377, in load
  File "build/bdist.macosx-10.13-intel/egg/pkg_resources/__init__.py", line 2383, in resolve
  File "build/bdist.macosx-10.13-intel/egg/smartthings_cli/smartthings_cli.py", line 36, in <module>
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/internet/default.py", line 50, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/internet/selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0-py2.7-macosx-10.13-intel.egg/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'

```
Running this on mac osx 10.13
python 2.7.10

**Comment by richyen** [comment]
Seems to be a `Twisted` versioning issue.  [Downgrading to 16.4.1](https://github.com/scrapy/scrapy/issues/2473) seemed to fix it
